site_name: Golem0
repo_url: https://github.com/ertrzyiks/golem0
pages:
- [index.md, Home]
- [core/world.md, Core, World]
- [core/entity.md, Core, Entity]
- [core/animation.md, Core, Animation]
- [pin/pin.md, Pins, Pin]
- [pin/output_pin.md, Pins, OutputPin]
- [pin/input_pin.md, Pins, InputPin]
- [devices/led.md, Devices, Led]
- [devices/button.md, Devices, Button]

theme: readthedocs
theme_dir: docs/theme
